### ISSUE TITLE
Can't install torchaudio 0.13.1

### ISSUE THREAD

**Issue by KintCark** [guoyww/AnimateDiff#358]
I'm trying to install this I tried all conda channels but I even did pip install torchaudio=0.13.1 but it still says package not found! Do I need to use an older version of python? I'm currently using python 3.10.12

(base) root@localhost:~/AnimateDiff# conda env create -f environment.yaml
Channels:
 - pytorch
 - nvidia
 - conda-forge
Platform: linux-aarch64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - torchaudio=0.13.1*

Current channels:

  - https://conda.anaconda.org/pytorch/linux-aarch64
  - https://conda.anaconda.org/nvidia/linux-aarch64
  - https://conda.anaconda.org/conda-forge/linux-aarch64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by nok** [comment]
Hello @KintCark , [in the past](https://pytorch.org/get-started/previous-versions/#linux-and-windows-18) it was available. 

As a workaround you can try to install the dependecy [`torchaudio` over pip](https://pypi.org/project/torchaudio/0.13.1/) by changing the environment file to this:

```yaml
name: animatediff
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=1.13.1
  - torchvision=0.14.1
  - pytorch-cuda=11.7
  - pip
  - pip:
    - torchaudio==0.13.1
    - diffusers==0.11.1
    - transformers==4.25.1
    - xformers==0.0.16
    - imageio==2.27.0
    - decord==0.6.0
    - gdown
    - einops
    - omegaconf
    - safetensors
    - gradio
    - wandb
```
