### ISSUE TITLE
horrible results when using sd 1.5

### ISSUE THREAD

**Issue by loboere** [guoyww/AnimateDiff#40]
I'm trying to run the base model without any dreambooth lora but the results are random or meaningless stuff

.yaml config
```
NewModel:
  path: ""
  base: ""

  motion_module:
    - "models/Motion_Module/mm_sd_v14.ckpt"
    - "models/Motion_Module/mm_sd_v15.ckpt"
    
  steps:          25
  guidance_scale: 7.5

  prompt:
    - "a girl"

  n_prompt:
    - ""
```

if something is wrong can you tell me how to configure it well for sd 1.5
